language: node_js
node_js:
  - "4"
env:
  global:
    - CXX=g++-4.8
    - secure: EqcwYYPSA12GIpGcP0XXFEpZZ6j3p5DCn76g04qpki2gDrjwRw6FTFcNJfM+B/Ku442zHgxzgBaTyrmaLDgtbvmr131CkO6SJuiTQ4CKluKcBk0m4eD/WNBTIdNOgEamWchW1MIpt1W/2kKVTwB07O8efxQSsRP80ADqBNMiZR6LBRVYpADazoqMSkbHDAer4PLzjzrIa6lgE+RQuPeNzEpdXv2394yNMXQxI287P0FlB/yOc6WfC/tfL13Mnr44Zf/6XITT261qCL9UXpSmfODTTaJNLkJ9j1xteS0jQLvHlgLtmJVGkRW1B1yNqLMhe4ZRTdtfNrK9Inl1x14j+OWocAoh8V8dFQOJLVDbbd/LkA7ZgGLw3WGv6RLmWRIO4vYCOYjmDoKbQR1Eszn+M127156pFGK3FihU6H1QTuhUyNWlNqnOu2sk2vVnHUNblNMIBYcauUcVyScQGydWEAsAqiJUgPxMqWnZ9Twmv8J01nt5AlBU+SyEQ2b7jAbaSUN8Q7od5mO93TDnae/PZoXWFL9RfszX8uges9dosqIxGN36qDVMF25UVJsQg7yMEBUNI3RDVfVuHG8nNXqWW/2c4hVS9wpBq3KCKc/ukyvszrX3L4bQMF85fZV5R3+7JacbpWei6BjPZBILCJhAoUzClWesLEapqlr945MrUQc=
    - secure: R3dSAsd9KcdigfWSjmzbqKtWLBfjQ5FRDsSC1nbsCebWD5hI6irUcdjR5W2nAdAsUKHwTIm8x0IGeoZhlWmt8PIJ9/HkKX78GM6My9wamF7xZVmLPt3Cn56QXsKvhVReUsqVzeeRvKi06pdOAS/IuQA/mctNQcv/+mbUL6hjB4mvpuO9e8O9r5kEepxDolifiM8VeIc1OdTN/wLfz4UCA7VMtIncyttMl6R3/JN93yWN1os+D+KH9KOimtEDzmnfLeMO6BBCecJegIgEhdQsqgFz/fUHqshAZwzoB9D6PXjhvnw3I3Rf8dobtP71y36+XQng8I/Pk6aSAGc+dUCT1s8R9X2Ug7U2GDTDim0LMVW6EVjUatsh+d8jlJRqLmPKEg+5hwdQNZ26rQT7EZ2QVc5cPpxJatRKIOGri6k1SpvYnC0Ch7Hg5iXGIwAlVHFaKC04uwnpxLzoYt5+qRMUzOle12DQZZgI9OIxylQCqzZdlhQWnmkE9tQE1xJZyDjGD1zHajYbXWZlJ3CD0tdnh3bdByG63zCDFOTvQnbI6sMYRl+qOjB1kFZJURRcdw6fBu7/SNlBugDxvD+v9ZtDObJTRMpGFGobM3chPzse//1eJ69uiDl0rEo3PU023AwbWnc0Iaq/4lLLA98ChXPsbL0cBwRs/pbe8m1ryvcrF24=
notifications:
  email: false
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - bower install
