language: node_js
node_js:
  - "4"
env:
  global:
    - CXX=g++-4.8
    - secure: G8jVT4zDxkVFlDzhD+mYRF/q+gJLdg71Sv/IPSHFYbl4zmbpUp7TyyePYblQ8oVRH6vkgT9dPoQU3Vr8YDlk2/xGwU5Fs8h6vqMvQ2c4jEkGvCTw+iy/hnbF6AQpQp5r7W62N1uzKnps2cujuVMEjlXWVrKuhq5PUB9MwY3vpetNRepN2F3fkJ+1j2bRHom6a7g/+U75pdm8NG8sCQ72H/7OQ0pi75ZjZZG8WC0uFuV3NCd2GJyrJrzI9FRlZX7lWou/uou2JC7qV1mwcDNUszVx3NRazzqezx+Aw4me/y9VWeJ2pcB0J8XvLocJTm8hkqoSPWUneRrXFfAg/rLGBbohzEh8i8JE0eow/LV12EL0YAApjmLMrY8FvROLyh4QVkzKWJhVae5pMer1MZQjrDPDY9BO339mx/cyTdW7I7nM4WuxP7VaoB61Q+mKB8rKVQmHekA5gLGPXVSjjJahcZ+XCM5RS4LEWxaKGib792y3FEsu/V5Fuvm/HN1CsO4s0bQ05MpD/hweeQktJPSDdQQbFUZcxt9tmOmhGHoao5eOvYkVME8aMvPBFHpprJ9GXy65F+0bm8Yl/GHrDuZmlZxXdIl/lsPjbEaNMjGUrelLvOCJVY2WHsOgoneeyvb+2rVI5KYSCYKZ+umbu/Gyha7DDVvICY/wdWSsRra6zgA=
    - secure: np601luFKtntaWbCZJ9kpYYUjob8Uu8xEndQNSaQDwazRCWGzdhlLbisaQID9JQRzWgyQbEi/xnEgVQjwahwljkedONpCbnJjrBaWn0Pa1yjAHoAbmTkR5GXpr7gBvpR4ML9Mp9xiuyrdPhrLy9zs5yOb6BDaAt7FTY/GLDO1UD+sdoW0ZsOB5yAmQ/svRHd97NsIaBJgM0yCJK0wfBzKfGdbdZZ35XnQ0Weq1pkWHAeIH176l7DsU4BOma+iLaW+LWLaxERdkvkG/fBDg8M+/E82Y+mWB7LFcpfrll2+NYzl/HDCrSwNc86gRgt9S6WYwS8+V3D9w408RV8hCqUdxkEz8Y/D08tEcqqG6HQ53rI79z6BPy0gCkZnR9xuu7AoX48WTuD2dbQPPRZfQIdavfcoP/IfQw0CUzW9BGVvQO+O1ZDIkAUe/q9PNJL5xBUTcwxb2ZAT5NLnxZ9eH75BGlTfRgjlNetigCz4f8MvHsBQCIMxCjwHGT+jBxqkGTX07LrbKXWm7NXvLK/rjbiHgV0GXZge1dLIYMWz2hc2kgMRbKgty5yMn42E7A4DluGvyuokZrYuz05oSy+/ABgRh1N82b3zugf+FEnwrd1snrHMtJ3DAOcHExVzk89HCoeb0r21XNRhZoQ0WfZ+RA/Tet9CHn5vp6fqDzAPD6sYWU=
notifications:
  email: false
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - bower install
