language: node_js
node_js:
  - "4"
env:
  global:
    - CXX=g++-4.8
    - secure: aFGqRvkLRoGDOhiNUdeA0LG172oYUYrQrA6FoOYUjw8NZ96IyOnTlBet0MX2LJnq1SAfManjKlIyAAwd0BvdTpaMC14F+yRbRuByKYLj17mj2Sgr9j92hJIeuSNvUlPp79S36V1vrmVZM4XfYzpAK8ibrJwjcov113Dz8Ss6Uxz6wb5xKWSylUt+C9KRdi2tnNpyuLhgPVaHYdGjXaWqoUdS5StuQJqcahiplSRRi4UEr9urXhnqvXsmBIKxWNyoe6MBUY7J1Fu9gm2gbbpl42/QNptvV0TYnTd3jaHVOyKhood1qY6frt2VQ26khgwXFvsI2TQjxBdWv6GRhBvYc+w+kR20h1wXFgWkhGb+3Ef19j0o7rqbnkBYHr6pIkYcubmygc4sX8MgEUOHKWqzz9v9Cs18FY2eIl9+F16j+IsuFTuF3T3ptuzyoRgjNpOk53QkI7k49xLW0GQtJiM9rCQOC76zCxDaRxiXBWi3VxXs/sWVazOBO1cKr2Lpu884wbNHGXA2CWuyta/yfwv1k63wZLKDM5WcSEmWPTFPwdJu6smBWNEG8A7odebVPquAEp6saPfcwELCI6ofdCPDi6IwHE1HpyVsmKAqCjrRsm7PaIzbIOO5O6AeDou//2IBS48P+p1FYuyccV3jF3fPilx6oHdYpfWO/udpwbrizkk=
    - secure: Nvf/YwYQnuY7I/injZ/jO7KVX4AvNC2Exx8U7CoLN9EfLKyDn5DJ7B1rGLc6yNgiz5wRcddTiwbG3Trmwkrq76GaXBAS/cW9dfI7Cgpt11dOh/w5ke75scRt8qOeVBv2oEFFWbp3NE5qvNtzN/aoiHVsStQf+nx/QWiQRedMwQ7Zr6Vwj+evuRB781SbvGjqYM9Sqv6HFtLfYUff9XFAv0Q/cdk8EPs7LVyZ+Aa0FE0Cb6gactiyOltFQ3j3O4e5IVc+03/ueAa+mHoyxqzMGSYh5BQZsx9aWaDMheCLgPKeuIFSsoMzlfqU58PJpDIDF1ftFr+QlPlBksqH0MkBq5iK/bEv9ZawpqdUEt8XxHl3GaC5HxsvgqXmaUDg79rsyVhVb5dyQhGna//HLoU2FGY8QokGIXS6C/cpJCUPOvG7cpONRR5UVwfn4pIhFsbde38xggzdX5lfR2RG4tl0TGn/dM+urBNuA1JnWq0bM9fm5jnlWHPZ8MEUbYxSw/hWzx2eDw/eTrVpGL3qylWTnsuxg9mFK/NxZNdCww5vJlLgEUcLRB2vn/EorbsjcSKetp3sE0VHVXY8Zu5xL8GFjw6M6dn+Fo3NAc92kM+yp+6/Qwi8ln/m005QuFKQn71rOQZd+MZ8pa3jWwpJZuERe1Y1u4vrpuCo3phxGN88BsQ=
notifications:
  email: false
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - bower install
